name: Azure Login Smoke (dev)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev   # ðŸ‘ˆ usa los secrets que pusiste en el environment dev
    steps:
      - name: Login en Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Mostrar cuenta activa
        run: az account show -o table

      - name: Estado actual de la VM
        run: |
          az vm get-instance-view \
            -g procesadorvm_group \
            -n procesadorvm \
            --query "instanceView.statuses[?starts_with(code,'PowerState/')].code" \
            -o tsv
